on: push
name: scrape on push
jobs:
  installDeps:
    name: install deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install deps
        run: npm ci 
      - name: send notification
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELE_GROUP_ID: ${{ secrets.TELE_GROUP_ID }}
          TELE_BOT_TOKEN: ${{ secrets.TELE_BOT_TOKEN }}